### ISSUE TITLE
Caught plotting error

### ISSUE THREAD

**Issue by fayhung** [fayhung/Caught-plotting-error#1]
Greetings,
Pls help me to solve this problem,
Tks.

Caught plotting error: Matches do not match with number of write entries 4295031324 4295031326
[3592] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by fayhung** [comment]
After changed HDD and SDD,
and I reinstalled the WIN10 system,
the problem still exists,
Could you help me to solve this problem, pls?
thank you so much.
